version: '3'
services:
  dd-agent:
    container_name: dd-agent
    image: "datadog/agent:latest"
    environment:
      - DD_SITE
      - DD_API_KEY
      - DD_HOSTNAME=obs-pipeline-myhost
      - DD_TAGS="lab:obs-pipeline"
      ## LOGS
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:dd-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
    networks:
      - my-dd-network
  deliverlah:
    container_name: deliverlah
    image: min99/deliverlah:latest
    networks:
      - my-dd-network
networks:
   my-dd-network:
     external: true
